### ISSUE TITLE
Insert is done when you call save

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#100]
When using non-native id, calling save() on a new domain object results in insert right away as gorm tries to get id from DB which is wrong. Previously, the insert was queued, and was executed when the session was flushed. This change on the behavior was introduced with fix for ticket https://github.com/grails/gorm-neo4j/issues/85.

https://github.com/grails/gorm-neo4j/blob/98334122d1955478c3c0454a5d79220870f83422/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/engine/Neo4jEntityPersister.java#L734

We'd need to have the former behavoir along with the fix for ticket 85.

**Comment by jameskleeh** [comment]
@AmaliaMV do you have an example app?

**Comment by AmaliaMV** [comment]
Hi @jameskleeh! 

if you want to debug HasManyInheritanceSpec, you can see that the insert is doing right away when the two SmartTelevision and the BasicTelevision are saved.

But when you try to save a ShoppingCentre, we have the expected behavior. The object is added to the pendingInsert collection.

**Comment by jameskleeh** [comment]
@AmaliaMV I've just pushed a fix to master that reverts the line in question and fixes the issue a different way. Please let me know if this meets your expectations.

**Comment by AmaliaMV** [comment]
@jameskleeh , I tested the change in grails/gorm-neo4j project and was working. When the new jar is available I will being test in our project.

**Comment by jameskleeh** [comment]
@AmaliaMV A new snapshot should be published. Let me know

**Comment by AmaliaMV** [comment]
@jameskleeh , I am testing in my project your changes of grails-datastore-gorm-neo4j-6.2.0

**Comment by AmaliaMV** [comment]
@jameskleeh , thanks! Every is working as we expect.
