### ISSUE TITLE
Clean proxies are being detected as dirty with 7.0.x release

### ISSUE THREAD

**Issue by matero** [grails/gorm-neo4j#105]
We have been using GORM for Neo4j in different versions, but when tried to upgrade to 7.0.x we had noted that it fails to do correct dirty checks on proxies that are clean, without any kind of modification.

We have look at the code looking for some differences in the DirtyCheckable trait, but nothing seems different, so maybe the problem is in the initialization of the proxies.

You can check the Integration test `dirtycheckeable.not.working.with.clean.proxies.FailureOfCleanProxySpec` at [GORM dirty check failing with clean proxies](https://github.com/matero/GORM-dirty-check-failing-with-clean-proxies).

**Comment by puneetbehl** [comment]
If the proxy is initialized then you need to unwrap before calling `isDirty` on the child. For example:
```
ProxyHandler proxyHandler
if ( proxyHandler.isInitialized(parent.child) {
   child = proxyHandler.unwrap(parent.child)
}
assert !child.isDirty()
```
