### ISSUE TITLE
When deleting an object GORM is cascade deleting wrong related objects

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#17]
Let's say we have the following classes:

`Club {
   String name
   hasMany = [players: Player] 
}`

`Player {
  String name
  belongsTo = [club: Club]
}`

`BoardMember {
  String name
  Club club
}`

when deleting a Club, it's deleting all the related BoardMember object's to that Club.
It seems that as the Player belongsTo relationship has the same name as the BoardMember , it's deleting both.

**Comment by graemerocher** [comment]
Please provide an example that reproduces the issue
