### ISSUE TITLE
Creating objects on PreInsert/PostInsert is not creating them in the db

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#19]
We have some listeners that listen to persistent events and try to create different objects on those events. It looks that these objects are not created at all using GORM standard functions. 
This seems to be a pretty basic use case, is there anything wrong in what we are doing?

You can see a sample project in https://github.com/mburak/neo4j-app. There we have a listener "OtherListener" that listens to PostInsert and tries to create a simple object. If you start the project on a empty database you will see that it should be creating some of these objects but looking at the database, they are not there.

**Comment by graemerocher** [comment]
Like all versions of GORM when persisting objects from an event listener you have to wrap the logic in a new session / transaction this is because the listeners are typically executed during a `flush()` which is an in-progress write operation.

**Comment by mburak** [comment]
Yeah it wasn't working doing a withNewSession either but I'll try again and let you know.

**Comment by mburak** [comment]
If you see that project, I added a withNewSession wrapping a Counter object creation, but it's not creating it on each insert.

**Comment by graemerocher** [comment]
After the changes in the above commits. This works for me:

```groovy
            Counter.withNewSession {
                Counter.withTransaction {
                    Counter counter = new Counter()
                    counter.name = "PreInsert ${event.entity.name}"
                    counter.count = new Date().time
                    counter.save(flush:true)                    
                }
            }
```

**Comment by mburak** [comment]
Do we need to add both withNewSession and withTransaction?

**Comment by graemerocher** [comment]
Yes
