### ISSUE TITLE
Using belongsTo is not deleting in cascade 

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#25]
Having this schema:

```
class Person {
  static hasMany = [addresses: Address]
}
class Address {
  belongsTo = Address
}
```

when deleting the person, it should delete all the related addresses, but it's not doing it.

**Comment by graemerocher** [comment]
Please provide an example, we already have tests that verify this behaviour https://github.com/grails/gorm-neo4j/blob/master/grails-datastore-gorm-neo4j/src/test/groovy/grails/gorm/tests/CascadingDeleteSpec.groovy#L35
