### ISSUE TITLE
Setting an association to null is not removing the relationship in the db

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#26]
We have a simple case where we have 
```
class Club {
        String name
        Country country
}
```
When we do the following in a club with an existing country:
``` 
club.country = null
club.save()
```
it's not removing the relationship as expected.

You can see an example of that in https://github.com/mburak/neo4j-app. There's an action in ClubController to remove the country from a club.

**Comment by nikuelias** [comment]
+1. Im having the same behavior.
