### ISSUE TITLE
Using find with a Date argument fails

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#3]
Trying to execute something like this on a Neo4j entity:

    Person.find("MATCH (n:`Person`) WHERE (n.`dueDate` = {value}) RETURN n", [value: new Date()])

is throwing this error:

    org.neo4j.driver.v1.exceptions.ClientException: Unable to convert java.util.Date to Neo4j Value.
	at org.neo4j.driver.v1.Values.value(Values.java:96)
	at org.neo4j.driver.v1.Values.value(Values.java:232)
	at org.neo4j.driver.internal.InternalTransaction.run(InternalTransaction.java:146)
	at grails.neo4j.Neo4jEntity$Trait$Helper.find(Neo4jEntity.groovy:267)
	at grails.neo4j.Neo4jEntity$Trait$Helper.find(Neo4jEntity.groovy:263)x

**Comment by graemerocher** [comment]
Since this is related to the driver I am not sure there is much we can do about it

**Comment by mburak** [comment]
Weren't you converting it to long or something before? It's weird that this was working previous to bolt.

**Comment by graemerocher** [comment]
Nope

**Comment by mburak** [comment]
I think I'll just convert it to long to make it work.

**Comment by KrishWorking** [comment]
I faced the same problem a couple of mins before and in my code I had dueDate as the unique identifier in Person class. Making that not unique worked for me.
