### ISSUE TITLE
Update to use Neo4j Driver v1.1.0

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#34]
Update to use Neo4j Driver v1.1.0 and Neo4j v3.1.0

**Comment by graemerocher** [comment]
This was already done here https://github.com/grails/gorm-neo4j/commit/f43de2bdec414c79cb9d8afc86b1b2a3145193b8#diff-c197962302397baf3a4cc36463dce5eaR27

**Comment by mburak** [comment]
@graemerocher I don't see that in master nor latest 6.0.x branch https://github.com/grails/gorm-neo4j/blob/master/build.gradle#L28

And actually the latest driver is v1.1.1

**Comment by graemerocher** [comment]
it is on master https://github.com/grails/gorm-neo4j/blob/master/build.gradle#L27 

The version on master is v1.1.0, I will look to upgrade to 1.1.1 soon.

It won't go into 6.0.x since we never upgrade to new major driver versions in a point release.

**Comment by mburak** [comment]
Ok, I got it. Thanks.
