### ISSUE TITLE
environmental settings aren't honored in application.yml

### ISSUE THREAD

**Issue by jmlittle** [grails/gorm-neo4j#4]
Presently, only global grails.neo4j.* settings are honored for configuration. For proper use of neo4j (bolt driver edition), we would need per environment settings, such as environments.development.neo4j.*, test, and production variants. 

Please see [https://github.com/jmlittle/envNeo] for sample project. The project implies that you have a neo4j 3.x service running at the default port, and in the sample project, the username/password of neo4j is used.

The error one receives when using an environmental settings block is the same as when one doesn't assign any neo4j settings within application.yml

`ERROR org.springframework.boot.SpringApplication - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'neo4jTransactionManager' while setting constructor argument with key [1]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'neo4jDatastore': Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.grails.datastore.gorm.neo4j.Neo4jDatastore]: Constructor threw exception; nested exception is org.neo4j.driver.v1.exceptions.ClientException: Authentication token must contain: 'scheme : basic' (ID:8D751B007CC145D2FD07055706D6D6C86EAE412C09B0009A31783E820FA92CB7)`

**Comment by graemerocher** [comment]
The configuration, at least in the example, is not nested under the `grails` block:

https://github.com/jmlittle/envNeo/blob/master/grails-app/conf/application.yml#L21

This translates to `neo4j.username` when it should be `grails.neo4j.username`

**Comment by jmlittle** [comment]
So would it work under the environment block of it has grails.* prefixing it?

**Comment by graemerocher** [comment]
I would imagine so

**Comment by jmlittle** [comment]
Seems to work. So, its

environments:
    development:
        dataSource:
            ###
        grails:
            neo4j:
                username:

**Comment by graemerocher** [comment]
right
