### ISSUE TITLE
Old relationships are not deleted

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#45]
Having this classes:

```
class Player  {

    String name
    Application application

    static mapping = {
        dynamicAssociations true
    }

}


class Application {

    String name
    String appVersion

    static constraints = {
        appVersion nullable: true
    }
}

```

I create a player1 with an Application app1. Then in a controller actuib I update the player's application to be app2 but in the database I see both relationships:
```
neo4j-sh (?)$ ls -a 48
:Player
*dateCreated =[1492546127413]
*lastUpdated =[1492546127413]
*name        =[player1]
*version     =[0]
(player1,48)-[:club]->(club2,47)
(player1,48)-[:APPLICATION]->(app2,45)
(player1,48)-[:APPLICATION]->(app1,44)
```

You can reproduce this by downloading the project at https://github.com/mburak/sampleapp, branch 'dup-assoc'.
1 - Start up the app
2 - Access rest controller action club/updatePlayer

**Comment by graemerocher** [comment]
The sample application has no controllers

**Comment by mburak** [comment]
Did you try the right branch? you need to checkout 'dup-assoc'

**Comment by graemerocher** [comment]
Nevermind I see the branch comment

**Comment by amadfida** [comment]
Does this PR look good for this issue?

https://github.com/grails/gorm-neo4j/pull/56

**Comment by graemerocher** [comment]
It hasn't been merged yet because the PR lacks a test
