### ISSUE TITLE
Set a dynamic collection association after clearing fails.

### ISSUE THREAD

**Issue by jsolari56** [grails/gorm-neo4j#58]
The following test fails in 6.0.x branch.

    def "test clear and set again dynamic collection association"() {
        setup:
        def cosima = new Pet(name: 'Cosima')
        def lara = new Pet(name: 'Lara')
        def fred = new Pet(name: 'Fred')
        cosima.buddies = [lara, fred]

        when:
        cosima.save()
        session.flush()
        session.clear()
        def pet = Pet.findByName("Cosima")
        pet.buddies.clear()
        pet.save(flush:true)
        session.clear()
        pet = Pet.findByName("Cosima")
        lara = Pet.findByName('Lara')
        pet.buddies = [lara]
        pet.save(flush:true)
        session.clear()
        pet = Pet.findByName("Cosima")
        def result = session.transaction.nativeTransaction.execute("MATCH (n:Pet {__id__:{1}})-[:buddies]->(l) return l", [cosima.id])

        then:"The relationship is empty"
        IteratorUtil.count(result) == 1
        pet.buddies instanceof Collection
        pet.buddies.size() == 1
        pet.buddies.first().name == 'Lara'

    }

**Comment by jsolari56** [comment]
This would be a possible fix.
[ISSUE-58.diff.zip.txt](https://github.com/grails/gorm-neo4j/files/1282471/ISSUE-58.diff.zip.txt)

Also, I would like to become a contributor.
Thanks

**Comment by graemerocher** [comment]
Thanks for the pull request
