### ISSUE TITLE
Orphan objects are not removed when removing them from parent collection  

### ISSUE THREAD

**Issue by mburak** [grails/gorm-neo4j#6]
Let's say we have:

```
class Person {
    static hasMany = [phones: Phone]
}

class Phone {
    String phoneNumber

   static belongsTo = Person
}
```

if we do this:

```
person1.removeFromPhones(phone1)
person1.update()
```

Shouldn't that delete the whole Phone object from the db in addition to the relationship? We don't see it's doing that.
We also tried to add some mapping like this:

```
static mapping = {
    phones cascade: "all-delete-orphan"
}
```

with no luck.

**Comment by graemerocher** [comment]
Orphan deletion is not implemented yet.. the cascade setting you refer to is hibernate only right now
