### ISSUE TITLE
No associations persisted using grails' neo4j plugin version 6.1.4

### ISSUE THREAD

**Issue by mvinas1977** [grails/gorm-neo4j#60]
I created a very basic application using grails 3.3.0 and neo4j plugin 6.1.4
I have the following domains:

```
class Person {

    static mapWith = "neo4j"

    String name
    Activity principalActivity

    static hasMany = [phones: Phone]
    
    static constraints = {
        name nullable: false, blank: false
        principalActivity nullable: true
    }

    static mapping = {
        dynamicAssociations true
        phones cascade: "all-delete-orphan"
    }
}

```
```
class Phone {

    static mapWith = "neo4j"
    
    String number

    static belongsTo = [person:Person]

    static constraints = {
        number nullable: false, blank: false
    }
}
```

```
class Activity {

    static mapWith = "neo4j"

    String description

    static constraints = {
        description nullable: false
    }
}
```

In BootStrap.groovy I'm creating initial data

```
class BootStrap {

    def init = { servletContext ->

        Phone phone3 = new Phone(number: '4451-1227')
        Phone phone4 = new Phone(number: '4452-1227')
        Phone phone5 = new Phone(number: '4453-1227')

        Person p1 = new Person(name: 'Person 1', principalActivity: new Activity(description: 'Jobless'))
        p1.addToPhones(number: '3333-2122')
        p1.save(failOnError: true)

        Person p2 = new Person(name: 'Person 2')
        p2.addToPhones(phone3)
        p2.addToPhones(phone4)

        Person p3 = new Person(name: 'Person 3')

        Person p4 = new Person(name: 'Person 4')
        
        //Creates a dynamic association one to one
        p4.mainPhone = phone5

        p2.save()
        p3.save()
        p4.save()
    }
```

In neo4j I got all Persons, Phones and the activity persisted correctly but without any relationship between them.

`neo4j> MATCH (n:`Person`) RETURN n;`
(:Person {name: "Person 1", version: 0})
(:Person {name: "Person 2", version: 0})
(:Person {name: "Person 3", version: 0})
(:Person {name: "Person 4", version: 0})

`neo4j> MATCH (n:`Activity`) RETURN n;`
(:Activity {description: "Jobless", version: 0})

`neo4j> MATCH (n:`Phone`) RETURN n;`
(:Phone {number: "3333-2122", version: 0})
(:Phone {number: "4451-1227", version: 0})
(:Phone {number: "4452-1227", version: 0})
(:Phone {number: "4453-1227", version: 0})

If you try to get all relationships of Person I will not get any

`neo4j> MATCH (n:`Person`)-[r]-() RETURN r;`
`neo4j> `

You can reproduce this running the application in [https://github.com/mvinas1977/sampleApp](https://github.com/mvinas1977/sampleApp)

**Comment by graemerocher** [comment]
Most likely reason is you need to surround your logic with a transaction

**Comment by mvinas1977** [comment]
Yes that was the issue
