### ISSUE TITLE
Neo4j 5.15.0 Incompatibility

### ISSUE THREAD

**Issue by xxLiuxx** [grails/gorm-neo4j#603]
Hi,

I'm planning on upgrading the neo4j version from 4.4.x to 5.15.0. When I start the service, it throws the following exception.

![Screenshot 2024-01-16 at 12 50 36 PM](https://github.com/grails/gorm-neo4j/assets/39300012/fedd04bd-e90e-4c15-98d5-a687d4b00857)

I know there are some major changes from 4 to 5 and am just wondering will the gorm-neo4j support 5 in the future. If yes, when can we expect to use the new version with gorm?

Thanks

**Comment by puneetbehl** [comment]
@guillermocalvo Can you please try updating to the version 5 in the branch `9.0.x` (the next major version)? And create issues for whatever is incompatible or removed? 

Based on the assessment, we can plan out work and estimate timelines?

**Comment by guillermocalvo** [comment]
Closed by #611

**Comment by zhangjingcat** [comment]
Hi @guillermocalvo , thanks for the fixing, may I know when will the fix be released? Thanks

**Comment by xxLiuxx** [comment]
Hi @puneetbehl, hope you are doing well. Can I ask when will the next major version with Neo4j 5 compatibility be released? Thanks!

**Comment by puneetbehl** [comment]
I'm in the middle of something right now. Let me get back to you on this soon.

**Comment by xxLiuxx** [comment]
> I'm in the middle of something right now. Let me get back to you on this soon.

Hi @puneetbehl, could I ask if there's any update on this? Thanks!

**Comment by xxLiuxx** [comment]
Hi @puneetbehl @guillermocalvo ,

Just wondering if there's an expected release date for the support of Neo4j v5?

Thanks!

**Comment by puneetbehl** [comment]
Sorry for the delayed response. I am currently not working on the Grails framework, nor do I have access to perform a release.
