### ISSUE TITLE
Allow no arg neo4j driver config options

### ISSUE THREAD

**Issue by amadfida** [grails/gorm-neo4j#62]
Neo4j driver team has added few additional config options such as,

`withEncryption()`
`withoutEncryption()`
`withLeakedSessionsLogging()`
`withConnectionLivenessCheckTimeout( long value, TimeUnit unit )`

Currently only single arg `with` methods are supported. It would be good to extend support for no args or more than one args.

**Comment by jameskleeh** [comment]
`withoutEncryption()` will not be able to be supported since it doesn't follow the builder pattern

**Comment by jameskleeh** [comment]
@amadfida Because method argument names are not available at runtime, you would need to specify the argument names as `arg#` for multiple parameters.

Example:

```
....connectionLivenessCheckTimeout.arg0: 10
....connectionLivenessCheckTimeout.arg1: "MINUTES"
```

Is that acceptable?

**Comment by amadfida** [comment]
Yeah as long there is a way.

**Comment by jameskleeh** [comment]
Done via https://github.com/grails/grails-data-mapping/pull/1036
