### ISSUE TITLE
Wrong Id on related object

### ISSUE THREAD

**Issue by mvinas1977** [grails/gorm-neo4j#64]
I have a very simple model

`class Club extends BaseGraphDomain {

    String name

    static constraints = {
        name nullable: false, blank: false, unique: true
    }
}`

`class Player extends BaseGraphDomain {

    String name
    Integer number

    static belongsTo = [club: Club]

    static constraints = {
        name nullable: false, blank: false, unique: true
        number nullable: false, validator: { it > 0 }
    }
}`

each Players belongs to a club

the problem is when you try to use a related object

  `Player player = Player.get(someId)

   print player.club`

 the related object, in this case club, has all its properties with right values, except id that is same one than the player one

you can reproduce it using this sampleApplication

[https://github.com/mvinas1977/neo4jSampleApp](https://github.com/mvinas1977/neo4jSampleApp)

if you do
[http://localhost:8080/players/show/4](http://localhost:8080/players/show/4)

it show a player, you can see that player-club's id is 4 same than player's id

`{"id":4,"dateCreated":"2017-11-28T19:17:35Z","lastUpdated":"2017-11-28T19:17:35Z","name":"Blass Armando Giunta","number":8,"club":{"id":4}}`

If you list clubs you will see that there is only one and its id is 0

[http://localhost:8080/clubs](http://localhost:8080/clubs)

`[{"id":0,"dateCreated":"2017-11-28T19:17:35Z","lastUpdated":"2017-11-28T19:17:35Z","name":"Boca Jrs"}]`

**Comment by rkimaoui** [comment]
I have the same problem. since i upgraded from 6.1.0 to 6.1.4.
