### ISSUE TITLE
Inheritance in hasMany relationship issue

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#71]
I have these classes:

```
class GeneralRule {

    static mapWith = "neo4j"

    String name
    List<GeneralAction> actions = []
    static hasMany = [actions: GeneralAction]
}

class ParticularRule extends GeneralRule {

    List<ParticularAction> actions = []
    static hasMany = [actions: ParticularAction]
}

class GeneralAction {

    static mapWith = "neo4j"

    String name
    static belongsTo = [GeneralRule]
}

class ParticularAction extends GeneralAction {

    Integer priority
    static belongsTo = [ParticularRule]
}

```

When I create and save theses objects:

```
new GeneralRule(name: 'generalRule1', actions: [new GeneralAction(name: 'generalAction1')]).save()
new ParticularRule(name: 'particularRule1', actions: [new ParticularAction(name: 'particularAction1', priority: 2)]).save()
```
I have an issue when the actions for a `ParticularRule`  is saved. If I make this query `MATCH (n:GeneralRule) -[m:ACTIONS]->(p) RETURN n, m, p;`, I can see the action class for `ParticularRule` is `GeneralAction` instance of `ParticularAction`.

Here the link to the [example app](https://github.com/AmaliaMV/neo4j-rules). You can see the class of the actions on http://localhost:8080/ too.

**Comment by AmaliaMV** [comment]
Maybe this can help.

![screenshot from 2018-03-08 16-20-23](https://user-images.githubusercontent.com/5392638/37210256-cd091ab2-2386-11e8-86a0-e8090212267e.png)

On the `for`, first it is inserted  the  `rules.ParticularAction` in `value` hashMap with `actions` as key, but in the next iteration, the value of `action` key change to `rules.GeneralAction`.

**Comment by jameskleeh** [comment]
@AmaliaMV Is this the response you expect to see from `/`?

```
[
  {
    "id": 40,
    "name": "generalRule1",
    "class": "class rules.GeneralRule",
    "actions": [
      {
        "name": "generalAction1",
        "class": "class rules.GeneralAction"
      }
    ]
  },
  {
    "id": 42,
    "name": "particularRule1",
    "class": "class rules.ParticularRule",
    "actions": [
      {
        "name": "particularAction1",
        "class": "class rules.ParticularAction"
      }
    ]
  }
]
```

**Comment by AmaliaMV** [comment]
@jameskleeh yes, that's what I expect.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/grails-data-mapping/commit/0bf609ac04cfde09605eda04abdd3630d98d13ff
