### ISSUE TITLE
Wrong id from Proxy

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#72]
I have these two classes:

```
class Club extends BaseGraphDomain {
   String name
   Person administrator
}

class Person extends BaseGraphDomain {
    String name
}
```

When I do this, I have a wrong id for person:
```
class ApplicationController {

     def index() {

        Club club = Club.list().first()
        Long administratorId = club.administrator.id // I get the club id  instead of person id
        Person administrator = Person.get(administratorId)

        respond([clubId: club.id, club: club, administratorId: administratorId, administrator: administrator])
    }
}
```
This is the response of http://localhost:8080/

```
{"clubId":2798,"club":{"id":2798,"dateCreated":"2018-03-16T16:59:38Z","administrator":{"id":2797},"lastUpdated":"2018-03-16T16:59:38Z","name":"Boca Jrs"},"administratorId":2798,"administrator":null}

```

Here is the example app: [link](https://github.com/AmaliaMV/neo4j-idProblem).

**Comment by amadfida** [comment]
@AmaliaMV can you please attach a simple app, and also what versions of NEO4J-GORM your re on?

**Comment by AmaliaMV** [comment]
Version of Neo4j: 6.1.6 (in the sample app, but I have the same problem with 6.2.0.BUILD-SNAPSHOT)
Sample app: https://github.com/AmaliaMV/neo4j-idProblem

**Comment by jameskleeh** [comment]
@AmaliaMV Please verify the latest version of gson views is being used. If not, upgrade and let me know if that resolves the problem

**Comment by AmaliaMV** [comment]
Hi @jameskleeh, I changed gson-view version to 1.2.8.BUILD-SNAPSHOT and I still have the problem. 

When I was debugging, I saw that when you try to get the id from administrator (which is a proxy), you recevied the `associationKey` (from `AssociationQueryProxyHandler`).

```
public abstract class EntityProxyMethodHandler extends GroovyObjectMethodHandler {
   // ...
    protected Object invokeEntityProxyMethods(Object self, String methodName, Object[] args) {
        if (methodName.equals(IS_PROXY_METHOD)) {
            return true;
        } else if (methodName.equals(GET_PROXY_KEY_METHOD) || methodName.equals(GET_ID_METHOD)) {

            return getProxyKey(self);  // <--- this is called when you want to get the id

        } else if (methodName.equals(IS_INITIALIZED_METHOD)) {
            return isProxyInitiated(self);
        } else if (methodName.equals(GET_TARGET_METHOD)) {
            return getProxyTarget(self);
        } else if (methodName.equals(INITIALIZE_METHOD)) {
            initializeProxyTarget(self);
            return Void.class;
        } else {

            return INVOKE_IMPLEMENTATION; // <--- this is returned when you want to get the name

        }
    } 
}
```

And the `associationKey` for the administrator proxy is the club's id.

**Comment by AmaliaMV** [comment]
Something that I forgot to highlight, the problem is inside the controller.

```
  Club club = Club.list().first()
  Long administratorId = club.administrator.id               // I get the club's id  instead of person's id
  Person administrator = Person.get(administratorId)   // null

```

**Comment by jameskleeh** [comment]
@graemerocher Is the correct behavior to unwrap the proxy if the `id` is requested because the relationship needs to be loaded to retrieve it?

**Comment by graemerocher** [comment]
the `id` stored doesn't necessarily reference the association id and shouldn't be used in any external form. Since Neo4j doesn't actually have foreign keys the lazy load mechanism wraps a query for the inverse entity and performs a query to retrieve the inverse entity using the `club` id

As far as I can see this is behaving as designed and for `administrator.id` to actually contain the administrator id would require an extra query which would degrade performance.

**Comment by AmaliaMV** [comment]
@graemerocher So, if I need to get the id in a situation like that, how can I do that?

**Comment by mvinas1977** [comment]
But, when you retrieve the related object data, Why you can't bring the id too?. It is like any other property. It can be done in same query

**Comment by jameskleeh** [comment]
@AmaliaMV You should join the relationship in the query if you know you will need data from it

**Comment by mvinas1977** [comment]
But we are using gorm, we are not writing any query

**Comment by jameskleeh** [comment]
@mvinas1977 I suggest you read the documentation regarding lazy loading http://gorm.grails.org/latest/neo4j/manual/index.html#lazyLoading

**Comment by graemerocher** [comment]
@mvinas1977 We could retrieve the associated id, but since unlike SQL with Neo4j there are no foreign keys pointing from one node to another node in order to retrieve the id on the other side we have to perform an additional query or perform a `OPTIONAL MATCH` to do a join at the Neo4j level which would degrade perform for every single other query you do when using GORM. 

Of course I understand this is surprising behaviour in comparison to GORM for SQL/Hibernate, but GORM cannot perform miracles.

**Comment by mvinas1977** [comment]
one more comment about this issue ... if you map the relationship as **lazy: false**, it is still returning worng id.

**Comment by AmaliaMV** [comment]
Hi @puneetbehl ,

I was testing the changes, but I still have the same problem when I ask for the id.  When you ask for the id the method which resolves the request is `EntityProxyMethodHandler.getPropertyBeforeResolving`.

In addition, I am using grails 3.3.3.

**Comment by AmaliaMV** [comment]
This is the example app: https://github.com/AmaliaMV/neo4j-idProblem

And yes, I changed the version of neo4j to 6.1.7.BUILD_SNAPSHOT

**Comment by puneetbehl** [comment]
@AmaliaMV please check now.

**Comment by AmaliaMV** [comment]
Hi @puneetbehl , I checked and now it is working. Thanks.
