### ISSUE TITLE
Nullifying one-to-one dynamic association doesn't work.

### ISSUE THREAD

**Issue by jsolari56** [grails/gorm-neo4j#73]
The following test in 6.0.x branch, added to SchemalessSpec, fails.

    def "Test nullifying dynamic single-ended relationship"() {
        setup:
        def cosima = new Pet(name: 'Cosima')
        def lara = new Pet(name: 'Lara')
        cosima.buddy = lara

        when:
        cosima.save()
        session.flush()
        session.clear()

        then:
        Pet.findByName("Cosima").buddy.name == "Lara"

        when:"The dynamic association is nullified"
        cosima = Pet.findByName("Cosima")
        cosima.buddy = null
        cosima.save()
        session.flush()
        session.clear()

        then:
        Pet.findByName("Cosima").buddy  == null
    }

**Comment by amadfida** [comment]
@jsolari56 can you confirm of this is on 6.0x.BRINQA-SNAPSHOT or main SNAPSHOT?

**Comment by jsolari56** [comment]
@amadfida Yes... this test also fails in 6.0.x.BRINQA branch.

**Comment by jameskleeh** [comment]
Fixed by https://github.com/grails/gorm-neo4j/commit/bfccebcea0bccd7c87d0b145962cb5dcd6dff2aa
