### ISSUE TITLE
Custom constraint is never called

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#75]
I have a custom constraint which I registered, but it's never called. I found if I have the hibernate plugin, all works ok (the custom constraint is called), but if I don't have it, the constraint is never called.

The constraint only checks that a property doesn't have uppercase letters. So, in my `BootStrap.groovy`  file has this:

```
   ConstraintRegistry gormValidatorRegistry

    def init = { servletContext ->

        gormValidatorRegistry.addConstraint(BarConstraint)

       //...
                foo1 = new Foo(prop: 'prop1')
                foo1.save(flush: true, failOnError: true)  // this line should be ok

       //...           
                foo2 = new Foo(prop: 'Prop2')
                foo2.save(flush: true, failOnError: true)  // this line should fail
       //...            
```

The line  `foo2.save(flush: true, failOnError: true)` doesn't fail. Here is the sample app: https://github.com/AmaliaMV/neo4j-customConstraintRegistry

But, if you uncomment from build.gradle file these lines 
```
   //  compile "org.grails.plugins:hibernate5"
  //  compile "org.hibernate:hibernate-core:5.1.5.Final"
```

works ok.

**Comment by puneetbehl** [comment]
In case you are using Neo4j without Hibernate then you need to use following:
```groovy
import example.BarConstraint
import example.Foo
import org.grails.datastore.gorm.neo4j.Neo4jMappingContext
import org.grails.datastore.gorm.validation.constraints.registry.DefaultValidatorRegistry

class BootStrap {

    Neo4jMappingContext neo4jMappingContext

    def init = { servletContext ->

        ((DefaultValidatorRegistry) neo4jMappingContext.validatorRegistry).addConstraint(BarConstraint)

        ...
}
```
