### ISSUE TITLE
Transient attribute is maked as dirty

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#76]
I have these classes

```
class Person {
    static mapWith = "neo4j"

    String name
    String title

    static transients = ['title']
}
```

When I do this:

```
class ApplicationController {

    def index() {
        Person person = Person.findByName('Benjamín')
        person.title = 'Sr.'
        assert person.dirtyPropertyNames == []
        ///...
```
the `title` property was marked as dirty.  

Here is the sample app: https://github.com/AmaliaMV/neo4j-transients

The versions I am using are: 
``` 
grailsVersion=3.3.5
gormVersion=6.1.10.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by jameskleeh** [comment]
What problem is this causing?

**Comment by AmaliaMV** [comment]
Our app use multiple threads. When a thread changes the value of the transient property of an object, this is marked as dirty. And when another thread need to save the object we have an optimistic locking, but the persistent properties wasn't changed by the first thread.

**Comment by puneetbehl** [comment]
@AmaliaMV please check now.

**Comment by AmaliaMV** [comment]
Perfect! it's working. Thanks!
