### ISSUE TITLE
Error when propertyMissing is called in a unit test

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#77]
I have the following unit test:

```
    void "test missing property"() {
        given:
        Person person = new Person(name: 'Benjamín').save(flush:true)

        when:
        String lastName = (String) person.propertyMissing('lastName')

        then:
        lastName == null

    }
```

And the Person class:
```
class Person extends BaseGraphDomain {

    String name

    def propertyMissing(String name) {
        super.propertyMissing(name)
    }
}
```

When I run the test, the following exception is thrown:

```
Cannot cast object 'example.Person' with class 'org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity' to class 'org.grails.datastore.gorm.neo4j.GraphPersistentEntity'
org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'example.Person' with class 'org.grails.datastore.mapping.keyvalue.mapping.config.KeyValuePersistentEntity' to class 'org.grails.datastore.gorm.neo4j.GraphPersistentEntity'
	at grails.neo4j.Neo4jEntity$Trait$Helper.getAt(Neo4jEntity.groovy:79)
	at grails.neo4j.Neo4jEntity$Trait$Helper.propertyMissing(Neo4jEntity.groovy:54)
	at example.Person.propertyMissing(Person.groovy:8)
	at example.PersonViewSpec.test missing property(PersonViewSpec.groovy:18)
```

However, when I run the app this error doesn't happen. 

Here is the sample app: https://github.com/AmaliaMV/neo4j-propertyMissing

The version I am using are:

``` 
grailsVersion=3.3.5
gormVersion=6.1.10.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by AmaliaMV** [comment]
I made your changes, except to change neo4j version, because I am working with 6.2.0.BUILD-SNAPSHOT.

I don't have the problem when I run the app, I only have this problem when I run the unit test.

**Comment by niravassar** [comment]
When you are running the app your application is probably be hooked up to a neo4j instance on localhost, correct? In a unit test, you need to use an embedded version with the configuration I specified. 

Also I am wondering what is the need to call propertMissing? Is it possible you are trying to make dynamicProperties at Runtime? If so, see this:

http://gorm.grails.org/latest/neo4j/manual/#schemaless

**Comment by AmaliaMV** [comment]
> In a unit test, you need to use an embedded version with the configuration I specified.

I added this 

```
grails:
    neo4j:
        type: embedded
```

in application.yml file, Is it ok?, but I sill have the problem. I was doing some changes on the unit test. If the dynamic property has a value for example

```
        Person person = new Person(name: 'Benjamín')
        person['lastName'] = 'García'
        person.save(flush: true)
```

All works well. But if  dynamic property value is null, I have the error.

> Also I am wondering what is the need to call propertMissing?

That's because we have overwritten this method in our classes. Something we need.
