### ISSUE TITLE
Error when controller response is render and you have a custom baseTemplateClass, in a unit test

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#78]
I have a custom baseTemplateClass which has a method like this:

```
abstract class BaseJsonView extends JsonViewWritableScript {

    String doSomething() {
        return "foo"
    }
}
```

This is my gson view:

```
model {
    Person person
}

json {
    name person.name
    foo doSomething()
}
```

When I run the app, I have the expected behavior, but when I run this unit test: 

```
    def "testing get1 action response"() {
        given:
        new Person(name: 'Úrsula').save(flush:true)

        when:
        controller.get1()

        then:
        response.json.toString() == '{"name":"Úrsula","foo":"foo"}'
    }
```

it fails because the actual response is:

```
Expected :{"name":"Úrsula","foo":"foo"}

Actual   :{"foo":{"writer":{}},"name":"Úrsula","doSomething":[]}
```

Here is the sample app: https://github.com/AmaliaMV/neo4j-controllerTest

The versions I am using are: 

```
grailsVersion=3.3.5
gormVersion=6.1.10.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
grailsViewsPluginVersion=1.2.7
```

**Comment by niravassar** [comment]
I see that you are extending the `JsonViewWritableScript `. I also tried to follow the docs where it advises to implement `JsonViewTemplate` to create a helper method. See here:

http://views.grails.org/latest/#_configuration 2.15.1. Changing the view base class and 2.15.2

I could not get that to work, nether. I am not sure why the extension of the JsonViewTemplate does not work. I will be looking into it further.

In the doc, 2.15.2. Adding New Helper Methods via Traits does work however. This will allow you to create a helper method and us in gson views. I added this class

```package example

import grails.artefact.Enhances
import grails.views.Views

@Enhances(Views.TYPE)
trait JsonViewMethods {

    String doSomething() {
        "foo from Trait"
    }
}
```

The test assert can be changed to `{"foo":"foo from Trait","name":"Úrsula"}`, as the response is from the trait method above.

**Comment by AmaliaMV** [comment]
I read the article which you recommended me, and I saw this: 

> The trait cannot be defined in the same project as you are compilation as it needs to be on the classpath of the project you are compiling. You will need to create a Grails plugin and use a multi-project build in this scenario.

I think it is a big change just because the unit tests related to the controllers do not work correctly.

> I could not get that to work, nether. I am not sure why the extension of the JsonViewTemplate does not work. I will be looking into it further.

Ok! perfect, I will wait.

**Comment by niravassar** [comment]
Yes that is written in the docs. However I did it in your project without creating a plugin. It also works. Just try that file in the same package as BaseJsonView and it worked for me.

**Comment by niravassar** [comment]
For the extension `JsonViewWritableScript`, this works in a full runnable app. Please confirm. The problem lies in the unit text context and setup. Some of the beans that are created at startup from the JsonViewGrailsPlugin need to be created at unit test runtime. 

In your `PersonControllerSpec`, add this to the top

```
    def setupSpec() {
        defineBeans(new JsonViewGrailsPlugin())
    }
```
with this added it should work.

**Comment by AmaliaMV** [comment]
Thanks!, it's working.
