### ISSUE TITLE
Validations on dynamic properties can't create message errors

### ISSUE THREAD

**Issue by matero** [grails/gorm-neo4j#80]
When a validation on a dynamic properties is not successful, it fails to build the error message as it can not access the property using the spring java-bean utilities.

When it tries to build the error message on dynamic properties, it throws a **NotReadablePropertyException** with the message _"Invalid property '$property' of bean class [$class]: Bean property '$property' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?"_

This only happens on dynamic properties, as shown on this [sample project](https://github.com/matero/gorm-neo4j-cant-report-errors) (see integration test PersonIntegrationSpec, on method 'it is not able to work dynamic properties').

**Comment by matero** [comment]
Is there any advance on this? Could I help in anyway?

**Comment by puneetbehl** [comment]
Not yet I will probably work on this today.

**Comment by puneetbehl** [comment]
I think what you are trying to achieve is not possible because we cannot modify the behavior of `rejectValue` as this is in Spring class. 

Apart from this, you can implement a custom validator (you would have to declare it on another non-dynamic property) and use `reject` to add an ObjectError instead of field error or alternatively register a custom validator using `mappingContext.addEntityValidator(..)` as follows:

```
void "it is not able to work dynamic properties"() {
        setup:
        neo4jMappingContext.addEntityValidator(Person.gormPersistentEntity, new Validator() {
            @Override
            boolean supports(Class<?> clazz) {
                return true
            }

            @Override
            void validate(Object target, Errors errorsList) {
                if (GrailsStringUtils.isBlank((String) target.email)) {
                    errorsList.reject(ConstrainedProperty.DEFAULT_BLANK_MESSAGE_CODE, [] as Object[], ConstrainedProperty.DEFAULT_BLANK_MESSAGE)
                }
            }
        })

        when: "validates an illegal value that needs to build its message"
        def sam = new Person(email: "")
        sam.email = ""
        sam.validate()

        then: "it fails"
        sam.errors.hasErrors()
    }
```
