### ISSUE TITLE
Problem with hasMany and inheritance + Custom Id Generator

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#85]
The problem is the same that I reported in https://github.com/grails/gorm-neo4j/issues/79. The difference is I have a custom id generator now. 

I was debbuging and I found when you don't have a nativeId this condition is false 

https://github.com/grails/gorm-neo4j/blob/88fe927c144ab2dab25f273b80e32231700ce3f3/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/engine/Neo4jEntityPersister.java#L100

and it is executing 

https://github.com/grails/gorm-neo4j/blob/88fe927c144ab2dab25f273b80e32231700ce3f3/grails-datastore-gorm-neo4j/src/main/groovy/org/grails/datastore/gorm/neo4j/engine/Neo4jEntityPersister.java#L228

![screenshot from 2018-05-17 16-48-16](https://user-images.githubusercontent.com/5392638/40200273-39db7d82-59f2-11e8-9e29-21e4529371e2.png)

I updated the example app. Here is the link: https://github.com/AmaliaMV/neo4j-hasManyInheritance

The versions I am using are:
```
grailsVersion=3.3.5
gormVersion=6.1.10.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by matero** [comment]
Is there any progress in this issue?

**Comment by puneetbehl** [comment]
@matero This is in progress. I found the problem and trying to figure out the solution. It is taking more time than what I anticipated.

**Comment by puneetbehl** [comment]
@AmaliaMV @matero  please check now

**Comment by AmaliaMV** [comment]
Perfect! It's working. Thanks!
