### ISSUE TITLE
Object is updated when you don't change anything.

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#93]
## Situation
I have an existing object (`Person`). 

```
class Person {

    String name
    Date lastUpdated
    Long version = 0L

  //...
}
```

I did a request to update this object, but actually I didn't change any property. So, I will expect there aren't changes in the object. However, the version number and the lastUpdated property changed.

## Steps to reproduce the error

1. Start the app.
2. Go to http://localhost:8080/person/index .
3. Press in 'Tomy' person. The version number should be 0.
4. Press the edit button.
5. Press the update button without change anything.
6. The version number should be 0, but is 1.

## Example app and plugins version

Here is the sample app: https://github.com/AmaliaMV/gorm-update

The versions I am using are:

```
grailsVersion=3.3.6
gormVersion=6.1.10.BUILD-SNAPSHOT
gradleWrapperVersion=3.5
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

This doesn't happen if I use hibernate instead of neo4j.

**Comment by jameskleeh** [comment]
@graemerocher In the hibernate example, the object gets passed through to https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-hibernate-core/src/main/groovy/org/grails/orm/hibernate/AbstractHibernateGormInstanceApi.groovy#L243

Hibernate must at that point determine not to do anything with it based on its dirty state.

The Neo4j impl uses the standard instance API which explicitly marks the instance as dirty on a call to `save()`. https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/org/grails/datastore/gorm/GormInstanceApi.groovy#L360. That code was added with this commit https://github.com/grails/grails-data-mapping/commit/34d80b5eaa06bc3e937829c188f50c25cf4377b6.

Which behavior is correct?

**Comment by jameskleeh** [comment]
@AmaliaMV The behavior has been added to GORM 6.1.11.BUILD-SNAPSHOT and both 6.1.x and 6.2.x neo4j snapshots. To change this behavior, set `grails.gorm.markDirty: false`. Please verify this works as you expect and I can close this issue.

**Comment by AmaliaMV** [comment]
@jameskleeh .. thanks! It's working as I expect. I close the ticket for you.
