### ISSUE TITLE
OptimisticLockingException

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#96]
**Problem**
When I try to update an object with an old version, I will expect an OptimisticLockingException.

I have this domain class:
```
class ModelA {

    String name

    Long version = 0L
    Date dateCreated
    Date lastUpdated
}
```

Also, I have a test:
```
void "Test the update action correctly updates an instance"() {
        when:"The save action is executed with valid data"
        def response = restBuilder.post(resourcePath) {
            json([name: "model A test"])
        }        

        then:"The response is correct"
        response.status == CREATED.value()
        response.json.id != null

        when:"The update action is called with valid data"
        def id = response.json.id
        def version = response.json.version
        def data1 = [name: "model A updated 1", version: version] 
        def data2 = [name: "model A updated 2", version: version] 

        response = restBuilder.put("$resourcePath/$id") {
            json(data1)
        }

        then:"The response is correct"
        response.status == OK.value()
        response.json

        when:"The update action is called with an old version"
        response = restBuilder.put("$resourcePath/$id") {
            json(data2)
        }

        then:"The response is incorrect"
        response.status == INTERNAL_SERVER_ERROR.value()

    }
```

However the result is:
![image](https://user-images.githubusercontent.com/5392638/46025622-c4552100-c0bf-11e8-879c-2bbd99fb575c.png)

I had a 200, but the exception was thrown anyway but after sending the response. 

The controller code:

```
    @Transactional
    def update() {
        ModelA modelA = modelAService.get(params.id)

        if (modelA == null) {
            render status: NOT_FOUND
            return
        }

        try {
            DataBindingUtils.bindObjectToInstance(modelA, new SimpleMapDataBindingSource(request.JSON), null, ['dateCreated'], null)
            modelAService.save(modelA)

        } catch (ValidationException e) {
            respond modelA.errors, view:'edit'
            return
        }

        respond modelA, [status: OK, view:"show"]
    }
```
Some comments: 
- Our update, save and delete methods are `Transactional`. In this case, the object isn't saved in Neo4j database when  `modelAService.save(modelA)` finished. On the other hand, if the method isn't transactional, the behavior is as expected. Is there a problem to have action's controller as  `Transactional`? 
- `setProperties()` doesn't bind the version property, that's why I am using  `DataBindingUtils.bindObjectToInstance()`

Here is the sample app: https://github.com/AmaliaMV/neo4j-optimisticLockingException

The versions I am using are:
```
grailsVersion=3.3.8
gormVersion=6.1.11.BUILD-SNAPSHOT
gradleWrapperVersion=3.5
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by jameskleeh** [comment]
@AmaliaMV What is the expected behavior?

You shouldn't be binding the version in any case. I'm not aware of any good reason to do that.

**Comment by AmaliaMV** [comment]
@jameskleeh , so what should be the correct way to verify the version before saving an object?

**Comment by AmaliaMV** [comment]
@jameskleeh ok, so what should be the correct way to check the version number? 

Currently, we use in some controllers setProperties(), but if we have an old version of an instance the OptimisticLockingException isn't thrown and the data is saved. I mean, if two users are updating the same object and one of them saves it first and the second one saves it later, the changes made by the second user overwrite those made by the first user.

In other cases, we use `DataBindingUtils.bindObjectToInstance()` and we are binding the version. But in this case, we have is that the OptimisticLockingException but is thrown after sending the response. So, the front-end receives a 200, instead of a 500.

**Comment by jameskleeh** [comment]
@AmaliaMV The version should be checked manually after loading the instance

```if (params.version < instance.version) {
   instance.errors.rejectValue...
}```

**Comment by AmaliaMV** [comment]
@jameskleeh, Thanks for the answer! Ok, so this isn't a bug, I will close the tickets. Thanks!
