### ISSUE TITLE
Loop in UniqueConstraint

### ISSUE THREAD

**Issue by AmaliaMV** [grails/gorm-neo4j#97]
After the last update of Gorm, our app doesn't work.

In our case, we have something like this:

`A <--- B <-- C`

`A` class has a property called `name`. `B` class has another property. And `C` class has the constraint `name unique:true`

When the app has to check the UniqueContraint an infinite loop starts.

![screenshot from 2018-10-10 14-17-30](https://user-images.githubusercontent.com/5392638/46754453-e0002000-cc98-11e8-81fe-1c54f30cf52c.png)

In line 65 of UniqueContraint.groovy, `mappingContext.getPersistentEntity(mappingContext.getProxyHandler().getProxiedClass(target).superclass.getName())` always returns a PersistentEntity related with `B ` class.

And in the `while` validation, the `property` (name) is inherited and the `targetEntity` isn't null. So the loop starts again, but the targetEntity is always the same.

Here is the sample app: https://github.com/AmaliaMV/gorm-uniqueConstraint

The versions I am using are:
```
grailsVersion=3.3.8
gormVersion=6.1.11.BUILD-SNAPSHOT
grailsNeo4jPluginVersion=6.2.0.BUILD-SNAPSHOT
```

**Comment by jameskleeh** [comment]
@AmaliaMV How do I reproduce the error?

**Comment by jameskleeh** [comment]
Nevermind - I had a local snapshot that was allowing it to run successfully

**Comment by AmaliaMV** [comment]
@jameskleeh, can you reproduce the error now?.. Just when you want to run the application, there should be the infinite loop.

**Comment by jameskleeh** [comment]
@AmaliaMV Yes
